#!/bin/bash

set -eu -o pipefail

sudo -n true

test $? -eq 0 || echo "you should have sudo privileges to run this script" && exit 1


RED='\033[0;31m'
NO_COLOR='\033[0m'
CLEAR_LINE='\r\033[K'

git clone https://github.com/cpotter302/aliasrc-shell.git

alias_path=~/.bash_aliases
bashrc_path="$HOME"/.bashrc

[ -f alias_path ] && echo "export ALIAS_RC_ROOT=$alias_path" >> "$bashrc_path"
source "$bashrc_path"
echo "# autogenerated by aliasrc" >> "$ALIAS_RC_ROOT"

printf "🔎   checking dependencies"

if ! command -v python3 >/dev/null  ||  ! command -v pip3 >/dev/null; then
  printf "%s💀%s  You must install python3 and pip3 on your system before setup can continue%s\n", \
  "${CLEAR_LINE}", "${RED}", "${NO_COLOR}"

  echo "To install automatically by the script enter 'yes'"
  read -r prompt
    if [[ $prompt =~ [yes|y] ]]; then
        sudo apt-get update
        apt install -y \
          python3 \
          pip3
    else
        printf "ℹ️   On Ubuntu-Linux🍎 you should 'sudo apt install python'\n"
        printf "Run script again after finishing to install missing dependencies" 
        exit 1
    fi
else
  sudo pip3 install -r ../requirements.txt
fi

mv "$PWD"/aliasrc-shell/alias.sh /bin/alirc && \
mv "$PWD"/aliasrc-shell/* /usr/lib/

sudo chmod +x /bin/alirc

printf "Succesfully installed aliasrc-shell"; echo "removing install script" && rm "$PWD"/install.sh
printf "view man pages for further instructions"


#TODO: Move bash file to /usr/bin and sources to