.\" Manpage for ali.
.\" Contact carlo.poetter@web.de to correct errors or typos.
.TH man 8 "30.12.2020" "1.0" "ali man page"
.SH NAME
alirc
.SH SYNOPSIS
alirc [OPTIONS]
.SH DESCRIPTION
This application is written in Python and the Bash-Scripting language and can be use as a handy commandline-tool for alias embedding. Use short commands and arguments to add new aliases, printing groups and deleting. No more nasty typing with several commands!
.SH OPTIONS
add alias:
        -a "ALIAS_NAME" -c "COMMAND_TO_EXECUTE"

print command group:
        -p -g "GROUP_NAME"

delete .bash_aliases file:
        -d

edit file with given editor:
        -e "DESIRED_EDITOR"

print whole file => .bash_aliases:
        -p print file

delete alias:
        -d -a "ALIAS_NAME"

delete whole group:
        -d -g "GROUP_NAME"

print specific alias:
        -p -a "ALIAS_NAME"

overwrite existing alias:
        -a -c -o
edit config:
        -s editor

look for help
        -h

.SH SEE ALSO
Nothing to see here

.SH BUGS
No known bugs.
.SH AUTHOR
Carlo Pötter (carlo.poetter@web.de)
