#!/bin/bash
free_space=$(df -h / | grep -E "\/$" | awk '{print $4}')
green_text="\033[32m"
bold="\033[1m"
normal="\033[0m"
logdate=$(date +"%d_%m_%Y")
logfile="$logdate"_ali.log

echo -e "$bold" "Quick system report for $green_text $HOSTNAME""$normal"
printf "\tSystem type: \t%s\n" "$MACHTYPE"
printf "\tBashVersion: \t%s\n" "$BASH_VERSION"
printf "\tFree Space: \t%s\n" "$free_space"
printf "\tFiles in dir: \t%s\n" "$(find . | wc -l)"
printf "\tGenerated on: \t%s\n" "$(date +"%d.%m.%Y")"
echo -e "$green_text""A summary of this info has been saved to $logfile""$normal"

cat <<- EOF > "$logfile"
        This report was automatically generated by my bash Script
EOF