name: package source files

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  zip_sources:
    name: Publish binaries
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: alirc-binaries
          path: ./
